### ISSUE TITLE
v0.0.3.8 DPS resetting as soon the boss dies

### ISSUE THREAD

**Issue by PunishedGrimm** [shalzuth/LostArkLogger#70] opened 2022-05-11 19:32 UTC
Pretty much the tittle, the new version is resetting when the boss dies istead when we leave the area.

**Comment by shalzuth** [comment] 2022-05-11 19:44
Duplicate of https://github.com/shalzuth/LostArkLogger/issues/55

**Closed by shalzuth** 2022-05-11 19:44 UTC
Labels: duplicate
